[service]
base_url = "https://7144-2409-40c2-205f-3324-9009-b45-f20f-1267.ngrok-free.app"
llm_url = "http://localhost"
signal_url = "https://d2k7cjzmjgpm6p.cloudfront.net/prod"

[logging]
sd_log_filename = "sd-miner.log"
llm_log_filename = "llm-miner.log"

[versions]
sd_version = "sd-v1.1.0"
llm_version = "llm-v1.0.0"

[storage]
s3_bucket = 'heurist-images'
base_dir = "~/.cache/heurist"

[model_config]
model_config_url = "https://raw.githubusercontent.com/heurist-network/heurist-models/main/models.json"
vae_config_url = "https://raw.githubusercontent.com/heurist-network/heurist-models/main/vae.json"

[system]
num_cuda_devices = 1
num_child_process = 8
sleep_duration = 2
min_deadline = 1
reload_interval = 600

[processing_limits]
max_iterations = 50
max_width = 1024
max_height = 1024
concurrency_soft_limit = 4
